WebAppWiki/Controllers/FiltersController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppWiki.BusinessLogic;
using WebAppWiki.BusinessLogic.Filters;
using WebAppWiki.Helpers;
using WebAppWiki.Models.Filters;

namespace WebAppWiki.Controllers
{
    public class FiltersController : Controller
    {
        private readonly ServiceFilter _serviceFilter;

        public FiltersController(ServiceFilter serviceFilter)
        {
            _serviceFilter = serviceFilter;
        }

        public IActionResult FiltersView()
        {
            var filter = HttpContext.Session.LoadObject<FilterMain>();

            var model = _serviceFilter.ProjectToModel(filter);

            return View(filter);
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ApplyFilterGameName(FilterMainModel model)
        {
            return UpdateFilter(model);
        }

        public IActionResult UpdateFilter(FilterMainModel model)
        {
            var filter = HttpContext.Session.LoadObject<FilterMain>();
            
            _serviceFilter.FiltersUpdate(filter, model);

            HttpContext.Session.SaveObject(filter);

			string? returnUrl = Url.Action("List", "Games");
			return Redirect(returnUrl);
		}
    }
}

WebAppWiki/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppWiki.Abstract;
using WebAppWiki.BusinessLogic.Filters;
using WebAppWiki.BusinessLogic;
using WebAppWiki.Domains;
using WebAppWiki.Helpers;
using WebAppWiki.Models;

namespace WebAppWiki.Controllers
{
    public class HomeController : Controller
    {
        private readonly ServiceFilter _serviceFilter;
        private readonly ILogger<HomeController> _logger;

        private readonly IRepository<Game, long> _repoGames;
        private readonly IRepository<Genre, long> _repoGenres;

        public HomeController(ServiceFilter serviceFilter, ILogger<HomeController> logger)
        {
            _serviceFilter = serviceFilter;
            _logger = logger;
            
        }

        public IActionResult Index()
        {
            var filter = HttpContext.Session
                .LoadObject<FilterMain>();

            var model = _serviceFilter
                .ProjectToModel(filter);

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppWiki/Views/Home/Index.cshtml
@model WebAppWiki.Models.Filters.FilterMainModel

@{
    ViewData["Title"] = "Главная страница";
}
<section class="wiki-hero py-4 py-md-5">
    <div class="container-xxl">
        <h1 class="display-5 fw-800 neon-title">@ViewData["Title"]</h1>
        <p class="lead text-secondary-500">Добро пожаловать на Вики!</p>
    </div>
    <div class="container-xxl">
        <form asp-controller="Filters" asp-action="ApplyFilterGameName" method="post" class="wiki-search mt-3">
            <div class="input-group input-group-lg">
                <input type="text" class="form-control wiki-search-input" value="@Model.FilterGame.GameName" id="FilterGame_GameName" name="FilterGame.GameName" placeholder="Найти игру..." aria-describedby="button-addon2">
                <button class="btn btn-outline-warning" type="submit" id="button-addon2">Искать</button>
            </div>
        </form>
    </div>
</section>